services:
  - type: web
    name: fastapi-ocr
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get update && sudo apt-get install -y tesseract-ocr tesseract-ocr-fra
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12